### ISSUE TITLE
[QUESTION] Run with `xelatex` or `lualatex`?

### ISSUE THREAD

**Issue by albertodiazdorado** [hegerdes/VSCode-LaTeX-Container#6]
Hi!

I have read through the docs but could not find and answer. Is it possible to configure the dev container to use `xelatex` or `lualatex` as an engine? I would like to use `fontspec` but `pdflatex` does not support it.

```
/usr/share/texlive/texmf-dist/tex/latex/fontspec/fontspec.sty:45: Fatal Package fontspec Error: The fontspec package requires either XeTeX or
(fontspec)                      LuaTeX.
(fontspec)                      
(fontspec)                      You must change your typesetting engine to,
(fontspec)                      e.g., "xelatex" or "lualatex" instead of
(fontspec)                      "latex" or "pdflatex".
```

**Comment by hegerdes** [comment]
Hi, thanks for opening this.

If you use the VSCode integration of this dev container, then you are using the LaTeX Workshop extension under the hood. 
Depending on your configuration it may have added a LaTeX symbol to your left sidebar. 
The extension uses "recipes" to complete your document. Several predifined recipes are already present, including xelatex. You can try some of them or build your own.

You might want to check out the docs of LaTeX workshop and the default recipe for more info: https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#building-the-document

**Comment by albertodiazdorado** [comment]
Thank you very much! I was able to make it work using the LaTeX workshop recipes setting
